In [2]:
import tensorflow as tf
print("TensorFlow Running.....")

TensorFlow Running.....


In [8]:
graph_1 = tf.Graph()

### Defining Constant

In [39]:
with graph_1.as_default():
    a = tf.constant([2], name="Constant_a")
    b = tf.constant([4], name="Constant_b")

In [40]:
a

<tf.Tensor 'Constant_a_1:0' shape=(1,) dtype=int32>

In [41]:
sess = tf.Session(graph=graph_1)
# result = sess.run(a + b)
print(sess.run(a))
# print("Final Result", result)
sess.close()

[2]


In [42]:
# with graph_1.as_default():
#     c = tf.add(a, b) 
c = tf.add(a, b)

In [47]:
sess = tf.Session(graph=graph_1)
print(sess.run(c))
sess.close()

[6]


In [50]:
q = tf.subtract(a, b)
with tf.Session(graph=graph_1) as sess:
    print(sess.run(q))


[-2]


In [56]:
graph_2 = tf.Graph()
with graph_2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )

with tf.Session(graph=graph_2) as sess:
    print(sess.run(Scalar))
    print("--------------")
    print(sess.run(Vector))
    print("--------------")
    print(sess.run(Matrix))
    print("--------------")
    print(sess.run(Tensor))

2
--------------
[5 6 2]
--------------
[[1 2 3]
 [2 3 4]
 [3 4 5]]
--------------
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [62]:
print(Matrix.shape)
Matrix.shape

(3, 3)


TensorShape([Dimension(3), Dimension(3)])

### Defining Variables in TensorFlow

In [63]:
m = tf.Variable(12)
n =tf.Variable(13)

In [64]:
inti = tf.global_variables_initializer()

In [65]:
with tf.Session() as sess:
    sess.run(inti)
    print(sess.run(m+n))

25


### Placeholder in TensorFlow

In [67]:
p = tf.placeholder(tf.float32)
q = p * 5

In [68]:
with tf.Session() as sess:
    print(sess.run(q, feed_dict={p:3.5}))

17.5
